### ISSUE TITLE
One Power Cell Galactic Search

### ISSUE THREAD

**Issue by dltompki** [gladiatorsprogramming1591/InfiniteRecharge2020-PBot#15]
# Proposed Functionality 
The robot drives from the start, picks up one power cell, and drives to the end. This should not require turning.

# Suggested Implementation 
Turn on intake mode, then drive the length of the field using the command from #10.

# Resources 
Issue #10

**Comment by jefft138** [comment]
Why is this labeled as testing? Did you start this one already, Dylan, even though it builds on #10 and that one is not started?
I'll be interested to see if the robot can intake the ball without slowing down.

**Comment by dltompki** [comment]
I labeled this testing because I see it as just an exercise in testing other features, not really being a feature itself. Let me know what you would have labeled it as. The system is definitely still WIP.
